### ISSUE TITLE
Add folder aliases

### ISSUE THREAD

**Issue by davestewart** [FranciscoKloganB/vitesse-enterprise#142]
Hey,

Well done on on setting up an enterprise structure; this is similar to how I build my projects too.

I see in your "nice to haves" you mentioned folder aliasing. You might want to consider [Alias HQ](https://github.com/davestewart/alias-hq) (one of mine) to expand on this.

You set up your aliases once only in `tsconfig.json` then choose an [integration](https://github.com/davestewart/alias-hq/blob/master/docs/integrations.md) for each toolchain, for example Vite:

```ts
import { defineConfig } from 'vite'
import hq from 'alias-hq'

export default defineConfig({
  resolve: {
    alias: hq.get('rollup')
  }
})
```

Anyway. Hope that's helpful.

**Comment by davestewart** [comment]
Though just noticed you're using `@` and `~` differently which a nice hack!

Anyway, if you needed to add a layer of deep linking such as `~utils` (rather than `~app/utils`) that's where Alias shines :)

**Comment by FranciscoKloganB** [comment]
Hello @davestewart, how are you?

First and foremost, sorry for the delay in answering your issue. I just came out of vacation and I am in a process of exchanging companies, so I have not paid much attention to the repository I would like.

Rest assured, I will look into this as soon as I have some availability. Your suggestions and feedback are greatly appreciated.

**Comment by FranciscoKloganB** [comment]
Hello @davestewart, after careful consideration I decided not to include `alias-HQ` on `vitesse-enterprise`, but I am using it on a small personal (private) project and am planning to use it to "refactor" the paths in an existing project of the new company I am in.

Thanks for letting me know about `Alias-HQ`.

:bow:

**Comment by davestewart** [comment]
Hey Francissco!

Sorry to take so long to get back to you; it's been on my list but I've been busy!

No worries. I'm glad it's helpful in your personal project, and thanks again for the your project!

Cheers,
Dave
