### ISSUE TITLE
Add unplug-vue-macros and other updates from vitesse

### ISSUE THREAD

**Issue by binaryfire** [FranciscoKloganB/vitesse-enterprise#359]
Thanks for sharing this template. We're finding it very helpful.

There have been a couple of updates to vitesse in the last year. Would you be able to add them?

- Add unplug-vue-macros packlage. See: https://github.com/antfu/vitesse/blob/75e627165659d615148a69fa2f43156e23f34ab8/package.json#L52 and https://vue-macros.sxzz.moe/
- Add vite-plugin-vue-component-preview package. See: https://github.com/antfu/vitesse/blob/75e627165659d615148a69fa2f43156e23f34ab8/package.json#L57
- Add starter Dockerfile. See: https://github.com/antfu/vitesse/blob/main/Dockerfile

I think that's all the changes... I may have missed something though

**Comment by FranciscoKloganB** [comment]
I will take a look into this in the weekend! :)
